on:
  push:
    branches:
      - main

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::282750940485:role/githubProviderRole
          aws-region: af-south-1
      - name: Package
        run: |
          npm i @actions/core
          npx ts-node --transpile-only src/index.ts
