on:
  push:
    branches:
      - main

name: Package

permissions:
  id-token: write
  contents: read

env:
  AWS_MAX_ATTEMPTS: 1
  NODE_OPTIONS: "--network-family-autoselection-attempt-timeout=1000"

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::282750940485:role/githubProviderRole
          aws-region: af-south-1
          audience: sts.amazonaws.com
      - name: Test get credentials from SecretsManager using local repo
        continue-on-error: true
        uses: georgeboc/aws-secretsmanager-get-secrets@refs/heads/main
        with:
          secret-ids:
            ANOTHER_TEST_CREDENTIALS_SECRETS_MANAGER, anothertest
          parse-json-secrets: true
