on:
  push:
    branches:
      - main

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Package
        run: |
          npx ts-node --transpile-only index.ts
