on:
  push:
    branches:
      - main

name: Package

permissions:
  id-token: write
  contents: read

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::282750940485:role/githubProviderRole
          aws-region: af-south-1
          audience: sts.amazonaws.com
      - name: Test get credentials from SecretsManager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids:
            TEST_CREDENTIALS_SECRETS_MANAGER, test
          parse-json-secrets: true
      - name: Package
        run: |
          npm i @actions/core
          npx ts-node --transpile-only src/index.ts
